<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <GeneratePkgDefFile>false</GeneratePkgDefFile>
    <CustomAfterMicrosoftCSharpTargets Condition="$(VsSDKInstall) != ''">$(VsSDKInstall)\Microsoft.VsSDK.targets</CustomAfterMicrosoftCSharpTargets>
    <IncludeAssemblyInVSIXContainer>false</IncludeAssemblyInVSIXContainer>
    <CopyBuildOutputToOutputDirectory>false</CopyBuildOutputToOutputDirectory>
    <StartAction>Program</StartAction>
    <StartProgram Condition="'$(DevEnvDir)' != ''">$(DevEnvDir)devenv.exe</StartProgram>
    <StartArguments>/rootsuffix Exp</StartArguments>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="languages.pkgdef">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="..\vscode\syntaxes\fusion.tmLanguage.json">
      <Link>syntaxes\fusion.tmLanguage.json</Link>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="..\vscode\fu-logo.png">
      <Link>fu-logo.png</Link>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="..\vscode\LICENSE">
      <Link>LICENSE</Link>
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <None Include="source.extension.vsixmanifest">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.14.40265" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="18.5.40034">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <Target Name="VsixSign" AfterTargets="CreateVsixContainer" Condition="'$(Configuration)' == 'Release'">
    <Exec Command="sign code certificate-store -cfp 89e22aa4003b327e1c68fdb8abc09e10e1cd3330e46119c795a99a6f55a48398 -csp &quot;Microsoft Smart Card Key Storage Provider&quot; -k A9109BEAA67F7E7DA4839BB34BEDA29A85CF5D8 -i -t http://time.certum.pl $(TargetVsixContainer)" />
  </Target>
</Project>
